# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.md']
sass:
    style: expanded


name: Palve

subtitle: Frontend Developer

title: Palve

robots:
    description: Palve's personal website.
    keywords: foo, bar, baz
    crawl: index,follow

url: https://palvef.github.io/  

baseurl: '/'

avatar: "https://avatars.githubusercontent.com/u/116693002"


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - xing:
      name: Xing
      show: false
      href: https://www.xing.com/profile/YOUR_XING_USERNAME/
      icon: fab fa-xing
  - linkedin:
      name: LinkedIn
      show: false
      href: https://linkedin.com/in/YOUR_LINKEDIN_USERNAME/
      icon: fab fa-linkedin
  - googleplus:
      name: Google+
      show: false
      href: https://plus.google.com/+YOUR_GOOGLEPLUS_USERNAME
      icon: fab fa-google-plus
  - twitter:
      name: Twitter
      show: false
      href: https://twitter.com/YOUR_TWITTER_USERNAME
      icon: fab fa-twitter
  - weibo:
      name: 微博
      show: false
      href: https://weibo.com/YOUR_WEIBO_USERNAME
      icon: fab fa-weibo
  - vine:
      name: Vine
      show: false
      href: https://vine.co/YOUR_VINE_USERNAME
      icon: fab fa-vine
  - facebook:
      name: Facebook
      show: false
      href: https://facebook.com/YOUR_FB_USERNAME
      icon: fab fa-facebook
  - vkontakte:
      name: ВКонтакте
      show: false
      href: https://vk.com/YOUR_VK_USERNAME
      icon: fab fa-vk
  - instagram:
      name: Instagram
      show: false
      href: https://instagram.com/YOUR_INSTAGRAM_USERNAME
      icon: fab fa-instagram
  - flickr:
      name: Flickr
      show: false
      href: https://flickr.com/photos/YOUR_FLICKR_USERNAME
      icon: fab fa-flickr
  - steam:
      name: Steam
      show: false
      href: http://steamcommunity.com/id/YOUR_STEAM_CUSTOM_ID
      icon: fab fa-steam
  - soundcloud:
      name: Soundcloud
      show: false
      href: https://soundcloud.com/YOUR_SOUNDCLOUD_USERNAME
      icon: fab fa-soundcloud
  - lastfm:
      name: Last.fm
      show: false
      href: http://www.last.fm/user/YOUR_LASTFM_USERNAME
      icon: fab fa-lastfm
  - github:
      name: GitHub
      show: true
      href: https://github.com/Palvef
      icon: fab fa-github
  - codepen:
      name: CodePen
      show: false
      href: https://codepen.io/YOUR_CODEPEN_USERNAME
      icon: fab fa-codepen
  - stackoverflow:
      name: Stack Overflow
      show: false
      href: https://stackoverflow.com/users/YOUR_SO_USERNAME/
      icon: fab fa-stack-overflow
  - reddit:
      name: Reddit
      show: false
      href: https://reddit.com/user/YOUR_REDDIT_USERNAME
      icon: fab fa-reddit
  - medium:
      name: Medium
      show: false
      href: https://medium.com/@YOUR_MEDIUM_USERNAME
      icon: fab fa-medium
  - tumblr:
      name: Tumblr
      show: false
      href: https://YOUR_TUMBLR_USERNAME.tumblr.com/
      icon: fab fa-tumblr
  - blog:
      name: Blog
      show: true
      href: https://www.palve.tech/blog
      icon: fas fa-book-open
  - email:
      name: Email
      show: true
      href: mailto:palve@palve.tech
      icon: fas fa-envelope
  - publickey:
      name: PGP Key
      show: false
      href: https://pastebin.com/raw/YOUR_PUBLIC_KEY
      icon: fas fa-key
  - telegram:
        name: Telegram
        show: true
        href: https://t.me/Palvef
        icon: fab fa-telegram


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
extra_html: >
    Any (multiline) text containing simple HTML,
    such as links or ... lorem ipsum.

#EOF
